### ISSUE TITLE
Error 500 when submitting amendment to text document

### ISSUE THREAD

**Issue by rukala** [liqd/adhocracy#965] opened 2015-08-04 10:34 UTC
I receive an Error 500 when trying to submit an amendment to a text document on tempelhofer-feld.berlin.de

URL: https://tempelhofer-feld.berlin.de/i/tempelhofer-feld/page/Parkordnung?overlay_path=%2Fi%2Ftempelhofer-feld%2Fpage%2FParkordnung_2%2Famendment.overlay&overlay_type=%23overlay-url-big

**Comment by xi** [comment] 2015-08-04 14:54
Duplicate of #950

**Closed as completed by xi** 2015-08-04 14:54 UTC
Labels: duplicate, bug, critical
